import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AlignLeft,
  BookOpen,
  Bot,
  Braces,
  Bug,
  Calculator,
  Check,
  CheckCheck,
  ChevronDown,
  CircleHelp,
  Clock3,
  Code2,
  Copy,
  Database,
  FileText,
  Fingerprint,
  Folder,
  Image,
  KeyRound,
  Languages,
  Link,
  List,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Megaphone,
  MessageSquare,
  Moon,
  MoreHorizontal,
  PanelLeftClose,
  Paperclip,
  Pencil,
  Plus,
  QrCode,
  RefreshCw,
  Ruler,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  Square,
  Sun,
  Table2,
  Trash2,
  Type,
  UserRound,
  Wrench,
  X,
  Binary,
  Palette,
  ExternalLink,
} from "lucide-react";
const icons = {
  download: ArrowDownToLine,
  back: ArrowLeft,
  arrow: ArrowRight,
  up: ArrowUp,
  align: AlignLeft,
  book: BookOpen,
  bot: Bot,
  braces: Braces,
  bug: Bug,
  calculator: Calculator,
  check: Check,
  checks: CheckCheck,
  chevron: ChevronDown,
  help: CircleHelp,
  clock: Clock3,
  code: Code2,
  copy: Copy,
  database: Database,
  file: FileText,
  fingerprint: Fingerprint,
  folder: Folder,
  image: Image,
  key: KeyRound,
  languages: Languages,
  link: Link,
  list: List,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  megaphone: Megaphone,
  chat: MessageSquare,
  moon: Moon,
  more: MoreHorizontal,
  collapse: PanelLeftClose,
  attachment: Paperclip,
  pen: Pencil,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  ruler: Ruler,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  stop: Square,
  sun: Sun,
  table: Table2,
  trash: Trash2,
  type: Type,
  user: UserRound,
  tools: Wrench,
  close: X,
  binary: Binary,
  palette: Palette,
  external: ExternalLink,
};
export function Icon({
  name,
  size = 19,
  className = "",
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Component = icons[name as keyof typeof icons] || Sparkles;
  return (
    <Component
      size={size}
      strokeWidth={1.7}
      aria-hidden="true"
      className={className}
    />
  );
}
