'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
type Message = { role:'user'|'assistant'; content:string };
type Chat = { id:string; title:string; messages:Message[]; updatedAt:number };
type View = 'chat'|'projects'|'agents'|'tasks'|'knowledge'|'tools';
const agents = [
  ['GM','General Manager','المدير العام'],['✉','Email Agent','وكيل البريد'],['⌕','DeepFind Research','وكيل البحث DeepFind'],['⌘','Developer Agent','وكيل التطوير'],['OP','Operations Agent','وكيل العمليات'],['MK','Marketing Agent','وكيل التسويق']
];
function makeChat():Chat { return { id: crypto.randomUUID(), title:'New conversation', messages:[], updatedAt:Date.now() }; }
export default function Home(){
  const [lang,setLang]=useState<'en'|'ar'>('en'); const [theme,setTheme]=useState<'dark'|'light'>('dark'); const [view,setView]=useState<View>('chat');
  const [chats,setChats]=useState<Chat[]>([]); const [active,setActive]=useState(''); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const ar=lang==='ar'; const t=(en:string,arabic:string)=>ar?arabic:en;
  useEffect(()=>{ try { const l=localStorage.getItem('oneshot-gimini:lang'); const th=localStorage.getItem('oneshot-gimini:theme'); if(l==='ar'||l==='en')setLang(l); if(th==='dark'||th==='light')setTheme(th); const saved=JSON.parse(localStorage.getItem('oneshot-gimini:chats')||'[]') as Chat[]; const initial=saved.length?saved:[makeChat()]; setChats(initial); setActive(localStorage.getItem('oneshot-gimini:active')||initial[0].id); } catch { const c=makeChat(); setChats([c]); setActive(c.id); } },[]);
  useEffect(()=>{ document.documentElement.dir=ar?'rtl':'ltr'; document.documentElement.lang=lang; document.documentElement.dataset.theme=theme; try{localStorage.setItem('oneshot-gimini:lang',lang);localStorage.setItem('oneshot-gimini:theme',theme)}catch{} },[ar,lang,theme]);
  useEffect(()=>{ if(chats.length)try{localStorage.setItem('oneshot-gimini:chats',JSON.stringify(chats));localStorage.setItem('oneshot-gimini:active',active)}catch{} },[chats,active]);
  const current=useMemo(()=>chats.find(c=>c.id===active)||chats[0],[chats,active]);
  const newChat=()=>{const c=makeChat();setChats(x=>[c,...x]);setActive(c.id);setView('chat');setError('')};
  const update=(messages:Message[])=>setChats(all=>all.map(c=>c.id===current?.id?{...c,messages,title:c.messages.length?c.title:(messages.find(m=>m.role==='user')?.content.slice(0,38)||c.title),updatedAt:Date.now()}:c));
  async function send(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||busy||!current)return;const next=[...current.messages,{role:'user' as const,content:text}];update(next);setInput('');setBusy(true);setError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');update([...next,{role:'assistant',content:d.text}]);}catch(err){setError(err instanceof Error?err.message:'Request failed')}finally{setBusy(false)}}
  const nav:[View,string,string][]=[['chat','✦',t('Chat','المحادثة')],['projects','▣',t('Projects','المشاريع')],['agents','◎',t('Agents','الوكلاء')],['tasks','✓',t('Tasks','المهام')],['knowledge','◇',t('Knowledge','المعرفة')],['tools','⌘',t('Tools','الأدوات')]];
  return <main className="app"><aside className="side"><button className="brand" onClick={()=>setView('chat')}><img src="/oneshot.svg" alt="OneShot"/><span>OneShot AI</span></button><button className="new" onClick={newChat}>＋ {t('New conversation','محادثة جديدة')}</button><nav>{nav.map(([v,i,label])=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><span>{i}</span>{label}</button>)}</nav><div className="recent"><b>{t('RECENT','الأخيرة')}</b>{chats.slice().sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,8).map(c=><button key={c.id} onClick={()=>{setActive(c.id);setView('chat')}}>{c.title}</button>)}</div><footer><span>1shotcam.com</span></footer></aside><section className="main"><header><button className="mobileBrand" onClick={()=>setView('chat')}><img src="/oneshot.svg" alt=""/>OneShot AI</button><div className="topActions"><button onClick={()=>setLang(ar?'en':'ar')}>{ar?'EN':'عربي'}</button><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀':'☾'}</button><span className="provider">✦ Gemini</span></div></header><div className="mobileNav">{nav.map(([v,i,label])=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><span>{i}</span><small>{label}</small></button>)}</div>
  {view==='chat'?<div className="chat"><div className="messages">{!current?.messages.length?<div className="hero"><img src="/oneshot.svg" alt=""/><h1>{t('One workspace. Every model. Every agent.','مساحة واحدة. كل النماذج. كل الوكلاء.')}</h1><p>{t('Web companion for your OneShot AI Android workspace.','نسخة الويب المرافقة لمساحة OneShot AI على أندرويد.')}</p></div>:current.messages.map((m,i)=><article key={i} className={m.role}><b>{m.role==='user'?t('You','أنت'):'OneShot AI'}</b><div>{m.content}</div></article>)}</div>{error&&<div className="error">{error}</div>}<form className="composer" onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={t('Message OneShot AI…','اكتب رسالتك إلى OneShot AI…')} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button disabled={busy||!input.trim()}>{busy?'…':'↑'}</button></form></div>:<Workspace view={view} ar={ar}/>}</section></main>
}
function Workspace({view,ar}:{view:View;ar:boolean}){const t=(e:string,a:string)=>ar?a:e;const cards:Record<View,[string,string][]>={chat:[],projects:[[t('Create project','إنشاء مشروع'),t('Persistent workspace for instructions, files and model choice.','مساحة مستمرة للتعليمات والملفات واختيار النموذج.')]],agents:agents.map(a=>[ar?a[2]:a[1],t('Start a dedicated AI work session.','ابدأ جلسة عمل متخصصة مع الوكيل.')]),tasks:[[t('Scheduled tasks','المهام المجدولة'),t('Recurring jobs and condition watches.','مهام متكررة ومراقبة الشروط.')]],knowledge:[[t('Company Knowledge','معرفة الشركة'),t('Brand, company and project memory.','هوية الشركة وذاكرة المشاريع.')]],tools:[[t('Integrations','التكاملات'),t('Gmail, Calendar, Drive, GitHub, Slack and local bridges.','Gmail وCalendar وDrive وGitHub وSlack والجسور المحلية.')]]};return <div className="workspace"><h1>{view[0].toUpperCase()+view.slice(1)}</h1><div className="grid">{cards[view].map(([a,b],i)=><div className="card" key={i}><div className="icon">{view==='agents'?agents[i]?.[0]:'✦'}</div><h3>{a}</h3><p>{b}</p><button>{t('Open','فتح')} →</button></div>)}</div></div>}
